apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scouter-java-agent
  namespace: scouter
  labels:
    app: scouter-agent-java
spec:
  selector:
    matchLabels:
      name: scouter-agent-java
  template:
    metadata:
      labels:
        name: scouter-agent-java
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: scouter-agent-java
        image: wlbebetter/scouter-agent-java:2.17.1
        volumeMounts:
        - name: scouter-agent-java-config
          mountPath: /opt/scouter/agent.java/conf
      volumes:
      - name: scouter-agent-java-config
        configMap:
          name: scouter-agent-java-config
