apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scouter-host-agent
  namespace: kube-system
  labels:
    app: scouter-host-agent
spec:
  selector:
    matchLabels:
      name: scouter-host-agent
  template:
    metadata:
      labels:
        name: scouter-host-agent
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: scouter-host-agent
        image: foobargem/scouter-agent-host:2.17.1
        volumeMounts:
        - name: scouter-host-agent-config
          mountPath: /scouter/conf
      volumes:
      - name: scouter-host-agent-config
        configMap:
          name: scouter-host-agent-config
